config/routes.rb
Rails.application.routes.draw do

  root 'home_page#index'

  resources :boat_attachments
  resources :boats do
    resources :rents
  end
  get 'home_page/index'
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :captains
  mount Commontator::Engine => '/commontator'

  get "boats/rent" => "boats#rent"

  get 'users/my_boats' => "users#my_boats"
  get 'users/my_rents' => "users#my_rents"

  get 'rents/confirm' => "rents#confirm"

  

  get 'cities/:state', to: 'application#cities'
  resources :rents

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :captain
  has_many :rent
  accepts_nested_attributes_for :captain
  acts_as_commontator       
end

app/controllers/user_controller.rb
# Skeleton for this code taken from a SO post.

class UsersController < ApplicationController
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @captain = @user.captain.create!(params[:captains])
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  private

  def user_params
    params.require(:user,:email,:pass_hash).permit(:setting1,:setting2,:etc)
  end

end

app/controllers/users_controller.rb
# Skeleton for this code taken from a SO post.

class UsersController < ApplicationController

  def my_boats
    @boats = Boat.where(ownerid: current_user.id)
  end

  def my_rents
    @rents = Rent.where(user_id: current_user.id)
  end



  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @captain = @user.captain.create!(params[:captains])
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  private

  def user_params
    params.require(:user,:email,:pass_hash).permit(:setting1,:setting2,:etc)
  end

end

app/views/users/my_boats.html.erb
<p id="notice"><%= notice %></p>

<h1>My Boats</h1>

<table style="width:50%">
  <thead>
  <tr>
    <th>Name</th>
    &nbsp;
    <th>Description</th>
    &nbsp;
    <th>Image</th>
    &nbsp;
    <th colspan="3"></th>
  </tr>
  </thead>
  <br>
  <tbody>
  <% @boats.each do |boat| %>
      <tr>
        <td><%= boat.name %></td>
        &nbsp;
        <td><%= boat.description %></td>
        &nbsp;
        <td><%= image_tag boat.boat_attachments[0].image.thumb.url %></td>
        &nbsp;
        <td><%= link_to 'Details', boat %></td>
        <td><%= link_to 'Edit', edit_boat_path(boat) %></td>
        <td><%= link_to 'Rent Requests', boat_rents_path(boat) %></td>
            &nbsp;
            <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  <p>

  </p>
  </tbody>
</table>

<br>

<%= link_to 'New Boat', new_boat_path %>

app/views/users/my_rents.html.erb
<p id="notice"><%= notice %></p>

<h1>My Rents</h1>

<table style="width:50%">
  <thead>
  <tr>
    <th>Boat id</th>
    &nbsp;
    <th>renting date</th>

    <th colspan="3"></th>
  </tr>
  </thead>
  <br>
  <tbody>
  <% @rents.each do |rent| %>
      <tr>
        <td><%= rent.boat_id %></td>
        &nbsp;
        <td><%= rent.date_required %></td>
        &nbsp;
      </tr>
  <% end %>
  <p>

  </p>
  </tbody>
</table>

<br>