config/routes.rb
Rails.application.routes.draw do

  root 'home_page#index'

  resources :boat_attachments
  resources :boats do
    resources :rents
  end
  get 'home_page/index'
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :captains
  mount Commontator::Engine => '/commontator'

  get "boats/rent" => "boats#rent"

  get 'users/my_boats' => "users#my_boats"
  get 'users/my_rents' => "users#my_rents"

  get 'rents/confirm' => "rents#confirm"

  

  get 'cities/:state', to: 'application#cities'
  resources :rents

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" style="background-color: #265af3f5">
    <div class="container-fluid">

        <div class="navbar-header">
        <span class="my-navbar-brand">Texas Boat Rental</span>
        </div>
        <ul class="nav navbar-nav">
   
            <li>
                <%= link_to "Home", root_path%>
            </li>

            <li>
                <%= link_to "Rent Boat", boats_path%>
            </li>

            <li>
            <% if user_signed_in? %>
                <%= link_to "Post Boat", new_boat_path%>
            <%else%>
                <%= link_to "Post Boat", new_user_session_path%>
            <%end%>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <% if !user_signed_in? %>
                    <%= link_to "Sign Up", new_user_registration_path%>
                <%end%>
            </li>


          <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              My Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" col-xs-12>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "My Rents", users_my_rents_path%></li>
              <li> <%= link_to "My Boats", users_my_boats_path%></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
            </ul>
          </li>
          <% end %>
            
            <li>
            <% if !user_signed_in? %>
                <%= link_to "Login", new_user_session_path%>
            <%end%> 
            </li>
        </ul>
    </div>
</nav>