config/routes.rb
Rails.application.routes.draw do

  root 'home_page#index'

  resources :boat_attachments
  resources :boats do
    resources :rents
  end
  get 'home_page/index'
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :captains
  mount Commontator::Engine => '/commontator'

  get "boats/rent" => "boats#rent"

  get 'users/my_boats' => "users#my_boats"
  get 'users/my_rents' => "users#my_rents"

  get 'rents/confirm' => "rents#confirm"

  

  get 'cities/:state', to: 'application#cities'
  resources :rents

end

app/models/boat_attachment.rb
class BoatAttachment < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :boat
  acts_as_commontable
end

app/controllers/boat_attachments_controller.rb
class BoatAttachmentsController < ApplicationController
  before_action :set_boat_attachment, only: [:show, :edit, :update, :destroy]

  # GET /boat_attachments
  # GET /boat_attachments.json
  def index
    @boat_attachments = BoatAttachment.all
  end

  # GET /boat_attachments/1
  # GET /boat_attachments/1.json
  def show
  end

  # GET /boat_attachments/new
  def new
    @boat_attachment = BoatAttachment.new
  end

  # GET /boat_attachments/1/edit
  def edit
  end

  # POST /boat_attachments
  # POST /boat_attachments.json
  def create
    @boat_attachment = BoatAttachment.new(boat_attachment_params)

    respond_to do |format|
      if @boat_attachment.save
        format.html { redirect_to @boat_attachment, notice: 'Boat attachment was successfully posted.' }
        format.json { render :show, status: :created, location: @boat_attachment }
      else
        format.html { render :new }
        format.json { render json: @boat_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boat_attachments/1
  # PATCH/PUT /boat_attachments/1.json
  def update
    respond_to do |format|
      if @boat_attachment.update(boat_attachment_params)
        format.html { redirect_to @boat_attachment, notice: 'Boat attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat_attachment }
      else
        format.html { render :edit }
        format.json { render json: @boat_attachment.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /boat_attachments/1
  # DELETE /boat_attachments/1.json
  def destroy
    @boat_attachment.destroy
    respond_to do |format|
      format.html { redirect_to boat_attachments_url, notice: 'Boat attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat_attachment
      @boat_attachment = BoatAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_attachment_params
      params.require(:boat_attachment).permit(:boat_id, :image)
    end
end

app/helpers/boat_attachments_helper.rb
module BoatAttachmentsHelper
end

app/views/boat_attachments/_form.html.erb
<%= form_for(@boat_attachment) do |f| %>
  <% if @boat_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boat_attachment.errors.count, "error") %> prohibited this boat_attachment from being saved:</h2>

      <ul>
      <% @boat_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= image_tag @boat_attachment.image %>
    <%= form_for(@boat_attachment) do |f| %>
        <div class="field">
          <%= f.label :image %><br>
          <%= f.file_field :image %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>

  <div class="field">
    <%= f.label :boat_id %><br>
    <%= f.number_field :boat_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boat_attachments/edit.html.erb
<h1>Editing Boat Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @boat_attachment %> |
<%= link_to 'Back', boat_attachments_path %>

app/views/boat_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boat Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Boat</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boat_attachments.each do |boat_attachment| %>
      <tr>
        <td><%= boat_attachment.boat_id %></td>
        <td><%= boat_attachment.image %></td>
        <td><%= link_to 'Show', boat_attachment %></td>
        <td><%= link_to 'Edit', edit_boat_attachment_path(boat_attachment) %></td>
        <td><%= link_to 'Destroy', boat_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boat attachment', new_boat_attachment_path %>

app/views/boat_attachments/new.html.erb
<h1>New Boat Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', boat_attachments_path %>

app/views/boat_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Boat:</strong>
  <%= @boat_attachment.boat_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @boat_attachment.image %>
</p>

<%= link_to 'Edit', edit_boat_attachment_path(@boat_attachment) %> |
<%= link_to 'Back', boat_attachments_path %>