config/routes.rb
Rails.application.routes.draw do

  root 'home_page#index'

  resources :boat_attachments
  resources :boats do
    resources :rents
  end
  get 'home_page/index'
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :captains
  mount Commontator::Engine => '/commontator'

  get "boats/rent" => "boats#rent"

  get 'users/my_boats' => "users#my_boats"
  get 'users/my_rents' => "users#my_rents"

  get 'rents/confirm' => "rents#confirm"

  

  get 'cities/:state', to: 'application#cities'
  resources :rents

end

app/models/boat.rb
class Boat < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader
  has_many :boat_attachments
  has_many :rents
  accepts_nested_attributes_for :boat_attachments
  #multiple images : https://stackoverflow.com/questions/21411988/rails-4-multiple-image-or-file-upload-using-carrierwave
  acts_as_commontable

  scope :state, -> (state) { where state: state }
  scope :city, -> (city) { where city: city }
  scope :capacity, -> (capacity) { where ("capacity > #{capacity} OR capacity = #{capacity}") }
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy, :remove_image]
  before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]
  before_filter :authenticate_user!

  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.all
    #filtering, may suffer from SQL injection.
    #https://www.justinweiss.com/articles/search-and-filter-rails-models-without-bloating-your-controller/
    @boats = @boats.state(params[:state]) if params[:state].present?
    @boats = @boats.city(params[:city]) if params[:city].present?
    @boats = @boats.capacity(params[:capacity]) if params[:capacity].present?
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
    #@boat_attachments = @boat.boat_attachments.all
    @boat_attachments = @boat.file_link.split(',')
    session[:boat_id] = @boat.id
    session[:boat_available_date] = @boat.available_date
  end

  # GET /boats/new
  def new
    @boat = Boat.new
    @boat_attachment = @boat.boat_attachments.build
  end

  def show_rents(id)
    @rents = Rent.where(boatid: id)
  end

  # GET /boats/1/edit
  def edit
  end
  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)
    @boat.owner_name = current_user.first_name + ' ' + current_user.last_name
    @boat.ownerid = current_user.id
    @boat.file_link = params[:boat][:file_position]
    @boat.video_link = params[:boat][:video_position]

    respond_to do |format|

      if @boat.save
        params[:boat_attachments]['image'].each do |a|
          @boat_attachment = @boat.boat_attachments.create!(:image => a)
        end
        #below notice will cause strange position for rent button, will fix this later
        #format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.html { redirect_to @boat}
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_boat
    @boat = Boat.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def boat_params
    params.require(:boat).permit(:ownerid, :name, :width, :depth, :height, :water, :capacity, :state, :city, :description, :available_date, :price, :location, :video, boat_attachments_attributes: [:id, :boat_id, :image])
  end

  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
  end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/_form.html.erb
<%= form_for(@boat, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
  <% if @boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% @boat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div style="display:flex; flex-wrap: wrap;">
  <div style="flex-grow: 7;">
  <div style="display:flex; flex-wrap: wrap;">
    <div class="field" style="padding-right: 2%;">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field" style="padding-right: 2%;">
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :capacity, 'Passenger capacity' %><br>
      <%= f.number_field :capacity %>
    </div>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :width, :placeholder => 'width' %>ft.  <%= f.number_field :depth, :placeholder => 'depth' %>ft. <%= f.number_field :height, :placeholder => 'height' %>ft.
  </div>
  <div style="display: flex; flex-wrap: wrap;">
    <div class="field" style="padding-right: 2%;">
      <%= f.label :location, 'Location' %><br>
      <%= f.text_field :location %>
    </div>
    
    <div style="margin-top:28px;padding-right: 2%;">
    <select id="states-of-country" name="boat[state]">
      <option id="no-state" value="">Select Your State</option>

      /* For states within US */
      <% CS.states(:us).each do |key, value| %>
          <option value="<%= value %>" id="<%= key %>"
          <% if value == @boat.state %> selected<% end %>><%= value; %></option>
      <% end %>
      @shippings = Shipping.where(:active => 1)
    </select></div>

    <div style="margin-top:28px;">
    <select id="cities-of-state" name="boat[city]" required>
      <option value="" selected>Select Your City</option>
    </select></div>
  </div>
  <div class="field">
    <%= f.label :water, 'Driven in' %><br>
    <%= f.select(:water, [ "salt water", "fresh water"] ) %>
  </div>
 
  <div class="field" style="width: 50%;">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <%= f.hidden_field :ownerid%>
  <%= f.hidden_field :owner_name%>
</div>
<div style="flex-grow: 6;">

    <div><%= f.label :available_date %><br></div>
    <div id="datepicker">
      <script type="text/javascript">
          $('#datepicker').datepicker({multidate:true});
          $('#datepicker').on('changeDate', function() {
              $('#boat_available_date').val(
                  $('#datepicker').datepicker('getFormattedDate')
              );
          });
      </script>
    </div>
    <input type="hidden" id="boat_available_date" name="boat[available_date]">

</div>
</div>

<div style="display: flex; flex-wrap: wrap">
  <%= f.fields_for :boat_attachments do |p| %>
    <div class="field">
      <%= p.label :image %><br>
      <%= p.file_field :image, :multiple => true, name: "boat_attachments[image][]" %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :video %><br>
    <%=f.file_field :video%>
  </div>

    <input type="hidden" id="file_position" name="boat[file_position]">
    <input type="hidden" id="video_position" name="boat[video_position]">

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boats/edit.html.erb
<h1>Editing Boat</h1>

<%= render 'form' %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boats</h1>

<table style="width:50%">
  <thead>
    <tr>
      <th>Name</th>
      &nbsp;
      <th>Description</th>
      &nbsp;
      <th>Image</th>
      &nbsp;
      <th colspan="3"></th>
    </tr>
  </thead>
<br>
  <tbody>
    <% @boats.each do |boat| %>
      <tr>
        <td><%= boat.name %></td>
        &nbsp;
        <td><%= boat.description %></td>
        &nbsp;
        <td><%= image_tag boat.boat_attachments[0].image.thumb.url %></td>
        &nbsp;
        <td><%= link_to 'Details', boat %></td>
        <% if boat.ownerid==current_user.id %>
        &nbsp;
        <td><%= link_to 'Edit', edit_boat_path(boat) %></td>
        &nbsp;
        <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    <p>

    </p>
  </tbody>
</table>

<br>

<%= link_to 'New Boat', new_boat_path %>

app/views/boats/new.html.erb
<h1>New Boat</h1>

<%= render 'form' %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>

<div class="media-post-page">
  <ul class="bxslider" >
    <% @boat_attachments.each do |p| %>
        <li><%= image_tag p, :controls =>true%></li>
    <% end %>
    <% if @boat.video_link != "" %>
        <li><video width="320" height="240" controls>
          <source src=<%= @boat.video_link.to_s%> type="video/mp4" autoplay="autoplay" loop="loop">
        </video></li>
    <% end %>
  </ul>
</div>


<div class="row">
  <div class="col-xs-2">
  </div>
  <div class="col-xs-5">
    <table class="post-page-table">
      <tbody>
      <tr>
        <td><strong>Name:</strong></td>
        <td><%= @boat.name %></td>
      </tr>
      <tr>
        <td><strong>Owner:</strong></td>
        <td><%= @boat.owner_name %></td>
      </tr>

      <tr>
        <td><strong>Dimensions:</td>
        <td>
          <%= @boat.width %> X
          <%= @boat.depth %> X
          <%= @boat.height %> ft.

        </td>
      </tr>

      <tr>
        <td><strong>Driven in:</strong></td>
        <td><%= @boat.water %></td>
      </tr>

      <tr>
        <td><strong>Capacity:</strong></td>
        <td><%= @boat.capacity %></td>
      </tr>

      <tr>
        <td><strong>State:</strong></td>
        <td><%= @boat.state %></td></tr>
      <tr><td><strong>City:</strong></td>
        <td><%= @boat.city %></td>
      </tr>


      <tr>
        <td><strong>Description:</strong></td>
        <td><%= @boat.description %></td>
      </tr>
      </tbody>
    </table>



  </div>


  <div class="col-xs-5">
    <%= form_tag(new_boat_rent_path(@boat), method: "get") do%>
        <p class="rentoption">

          <strong>Dates Available </strong>

          <%= hidden_field_tag "available_date", @boat.available_date, { :id => "available-date" } %>

        <div id="datepicker">
          <script type="text/javascript">
              $('#datepicker').on('changeDate', function() {
                  $('#boat_chosen_date').val(
                      $('#datepicker').datepicker('getFormattedDate')
                  );
              });
          </script>
        </div>
        <input type="hidden" id="boat_chosen_date" name="chosen_date">

        <%= submit_tag("Rent", :type => :image, :src => "/assets/rent-now-button.png", :class => "rentbutton", :width => "15%") %>
        </p>

    <% end %>
  </div>
</div>

<div class="post-page-lower">
  <%= commontator_thread(@boat) %>
  <% if @boat.ownerid==current_user.id %>
      <%= link_to 'Edit', edit_boat_path(@boat) %> |
  <% end %>
  <%= link_to 'Back', boats_path %>
</div>